edit_icon = "//app-profile-details//i[contains(@class,'la la-pencil')]"
company_name_field = "//input[@name='companyName']"
company_act_dropdown = "//select[@name='companyAct']"
established_year_dropdown = "//select[@name='establishedYear']"
financial_year_radio = "//input[@value='0']"
company_type_dropdown = "//select[@name='type']"
director_identification_field = "//input[@name='directorIdentificationNo']"
mail_alias_field = "//input[@placeholder='abc@xyz.com']"
pfno_field = "//input[@name='pfNo']"
tan_field = "//input[@name='tanNo']"
pan_field = "//input[@name='panNo']"
esi_field = "//input[@name='esiNo']"
lin_field = "//input[@name='linNo']"
gst_field = "//input[@name='gstNo']"
registration_certificate_field = "//input[@name='registrationCertificateNo']"
turnover_field = "//input[@name='turnover']"
notice_period_dropdown = "//label[normalize-space()='Default']"
notice_period_field = "//label[normalize-space()='Default']"

company_logo_upload = "//div[contains(@class,'m-section')]//div[1]//a[1]//span[1]//span[1]"
company_signature_upload = "//a[contains(@data-target,'#m_imageUploadModal')]//span//span[contains(text(),'Upload')]"
company_nav_logo_upload = "//a[@class='btn btn-warning m-btn m-btn--icon']"

update_btn = "//button[normalize-space()='Update']"
